// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomePage1
void ui_HomePage1_screen_init(void);
void ui_event_HomePage1(lv_event_t * e);
lv_obj_t * ui_HomePage1;
void ui_event_ClockNumberLabel(lv_event_t * e);
lv_obj_t * ui_ClockNumberLabel;
void ui_event_DateLabel(lv_event_t * e);
lv_obj_t * ui_DateLabel;


// SCREEN: ui_HomePage2
void ui_HomePage2_screen_init(void);
void ui_event_HomePage2(lv_event_t * e);
lv_obj_t * ui_HomePage2;
void ui_event_ClockNumberLabel2(lv_event_t * e);
lv_obj_t * ui_ClockNumberLabel2;
void ui_event_DateLabel2(lv_event_t * e);
lv_obj_t * ui_DateLabel2;


// SCREEN: ui_Navigation
void ui_Navigation_screen_init(void);
void ui_event_Navigation(lv_event_t * e);
lv_obj_t * ui_Navigation;
lv_obj_t * ui_SettingPic;
lv_obj_t * ui_SettingLabel;
void ui_event_DrainPic(lv_event_t * e);
lv_obj_t * ui_DrainPic;
lv_obj_t * ui_DrainLabel;
lv_obj_t * ui_ClockPic;
lv_obj_t * ui_ClockLabel;
lv_obj_t * ui_NFCPic;
lv_obj_t * ui_NFCLabel;
void ui_event_MusicPic(lv_event_t * e);
lv_obj_t * ui_MusicPic;
lv_obj_t * ui_MusicLabel;
lv_obj_t * ui_CalculatorPic;
lv_obj_t * ui_CalculatorLabel;
lv_obj_t * ui_BluetoothPic;
lv_obj_t * ui_WifiPic;
void ui_event_Calendar(lv_event_t * e);
lv_obj_t * ui_Calendar;


// SCREEN: ui_MessageArc
void ui_MessageArc_screen_init(void);
void ui_event_MessageArc(lv_event_t * e);
lv_obj_t * ui_MessageArc;
lv_obj_t * ui_StepArc;
lv_obj_t * ui_TempatureArc;
lv_obj_t * ui_HumidityArc;
lv_obj_t * ui_Stepimg;
lv_obj_t * ui_Tempimg;
lv_obj_t * ui_Humidimg;
void ui_event_HumidArcLabel(lv_event_t * e);
lv_obj_t * ui_HumidArcLabel;
void ui_event_TempArcLabel(lv_event_t * e);
lv_obj_t * ui_TempArcLabel;
void ui_event_StepArcLabel(lv_event_t * e);
lv_obj_t * ui_StepArcLabel;


// SCREEN: ui_Music
void ui_Music_screen_init(void);
void ui_event_Music(lv_event_t * e);
lv_obj_t * ui_Music;
lv_obj_t * ui_Image6;
lv_obj_t * ui_MusicControl;
lv_obj_t * ui_Next;
lv_obj_t * ui_Back;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1009570679[1] = {&ui_img_1452209827};
const lv_img_dsc_t * ui_imgset_1589262468[1] = {&ui_img_230494180};
const lv_img_dsc_t * ui_imgset_851039223[1] = {&ui_img_1071127293};
const lv_img_dsc_t * ui_imgset_iu[1] = {&ui_img_iu1_png};
const lv_img_dsc_t * ui_imgset_iu_bg[2] = {&ui_img_iu_bg2_png, &ui_img_iu_bg3_png};
const lv_img_dsc_t * ui_imgset_1714125275[1] = {&ui_img_178944631};
const lv_img_dsc_t * ui_imgset_244861655[1] = {&ui_img_1364712013};
const lv_img_dsc_t * ui_imgset_setting[1] = {&ui_img_setting1_png};
const lv_img_dsc_t * ui_imgset_wifi[1] = {&ui_img_wifi1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_HomePage1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HomePage2_screen_init);
        _ui_screen_delete(&ui_HomePage1);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Navigation, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Navigation_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MessageArc, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MessageArc_screen_init);
    }
}
void ui_event_ClockNumberLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Home_Time(e);
    }
}
void ui_event_DateLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Home_Date(e);
    }
}
void ui_event_HomePage2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HomePage1_screen_init);
        _ui_screen_delete(&ui_HomePage2);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Navigation, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Navigation_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MessageArc, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MessageArc_screen_init);
    }
}
void ui_event_ClockNumberLabel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Home_Time(e);
    }
}
void ui_event_DateLabel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Home_Date(e);
    }
}
void ui_event_Navigation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_HomePage1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage1_screen_init);
    }
}
void ui_event_DrainPic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Motor_Toggle(e);
    }
}
void ui_event_MusicPic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Music, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Music_screen_init);
    }
}
void ui_event_Calendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Navi_Date(e);
    }
}
void ui_event_MessageArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_HomePage1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Music, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Music_screen_init);
    }
}
void ui_event_HumidArcLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Humidity_Arc(e);
    }
}
void ui_event_TempArcLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Tempature_Arc(e);
    }
}
void ui_event_StepArcLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Update_Step_Arc(e);
    }
}
void ui_event_Music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_HomePage1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MessageArc, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MessageArc_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomePage1_screen_init();
    ui_HomePage2_screen_init();
    ui_Navigation_screen_init();
    ui_MessageArc_screen_init();
    ui_Music_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomePage1);
}
