// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#ifndef _QI_WATCH_UI_H
#define _QI_WATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_HomePage1
void ui_HomePage1_screen_init(void);
void ui_event_HomePage1(lv_event_t * e);
extern lv_obj_t * ui_HomePage1;
void ui_event_ClockNumberLabel(lv_event_t * e);
extern lv_obj_t * ui_ClockNumberLabel;
void ui_event_DateLabel(lv_event_t * e);
extern lv_obj_t * ui_DateLabel;
// SCREEN: ui_HomePage2
void ui_HomePage2_screen_init(void);
void ui_event_HomePage2(lv_event_t * e);
extern lv_obj_t * ui_HomePage2;
void ui_event_ClockNumberLabel2(lv_event_t * e);
extern lv_obj_t * ui_ClockNumberLabel2;
void ui_event_DateLabel2(lv_event_t * e);
extern lv_obj_t * ui_DateLabel2;
// SCREEN: ui_Navigation
void ui_Navigation_screen_init(void);
void ui_event_Navigation(lv_event_t * e);
extern lv_obj_t * ui_Navigation;
extern lv_obj_t * ui_SettingPic;
extern lv_obj_t * ui_SettingLabel;
void ui_event_DrainPic(lv_event_t * e);
extern lv_obj_t * ui_DrainPic;
extern lv_obj_t * ui_DrainLabel;
extern lv_obj_t * ui_ClockPic;
extern lv_obj_t * ui_ClockLabel;
extern lv_obj_t * ui_NFCPic;
extern lv_obj_t * ui_NFCLabel;
void ui_event_MusicPic(lv_event_t * e);
extern lv_obj_t * ui_MusicPic;
extern lv_obj_t * ui_MusicLabel;
extern lv_obj_t * ui_CalculatorPic;
extern lv_obj_t * ui_CalculatorLabel;
extern lv_obj_t * ui_BluetoothPic;
extern lv_obj_t * ui_WifiPic;
void ui_event_Calendar(lv_event_t * e);
extern lv_obj_t * ui_Calendar;
// SCREEN: ui_MessageArc
void ui_MessageArc_screen_init(void);
void ui_event_MessageArc(lv_event_t * e);
extern lv_obj_t * ui_MessageArc;
extern lv_obj_t * ui_StepArc;
extern lv_obj_t * ui_TempatureArc;
extern lv_obj_t * ui_HumidityArc;
extern lv_obj_t * ui_Stepimg;
extern lv_obj_t * ui_Tempimg;
extern lv_obj_t * ui_Humidimg;
void ui_event_HumidArcLabel(lv_event_t * e);
extern lv_obj_t * ui_HumidArcLabel;
void ui_event_TempArcLabel(lv_event_t * e);
extern lv_obj_t * ui_TempArcLabel;
void ui_event_StepArcLabel(lv_event_t * e);
extern lv_obj_t * ui_StepArcLabel;
// SCREEN: ui_Music
void ui_Music_screen_init(void);
void ui_event_Music(lv_event_t * e);
extern lv_obj_t * ui_Music;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_MusicControl;
extern lv_obj_t * ui_Next;
extern lv_obj_t * ui_Back;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_iu_bg_png);    // assets/iu_bg.png
LV_IMG_DECLARE(ui_img_iu_bg3_png);    // assets/iu_bg3.png
LV_IMG_DECLARE(ui_img_setting1_png);    // assets/setting1.png
LV_IMG_DECLARE(ui_img_drain_png);    // assets/drain.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/clock.png
LV_IMG_DECLARE(ui_img_card_png);    // assets/card.png
LV_IMG_DECLARE(ui_img_cat_png);    // assets/cat.png
LV_IMG_DECLARE(ui_img_calculator_png);    // assets/Calculator.png
LV_IMG_DECLARE(ui_img_blue_png);    // assets/blue.png
LV_IMG_DECLARE(ui_img_closewifi_png);    // assets/closewifi.png
LV_IMG_DECLARE(ui_img_wifia_png);    // assets/WIFIa.png
LV_IMG_DECLARE(ui_img_step_png);    // assets/step.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/temp.png
LV_IMG_DECLARE(ui_img_materialsymbolshumiditypercentage_png);    // assets/MaterialSymbolsHumidityPercentage.png
LV_IMG_DECLARE(ui_img_iu1_png);    // assets/IU1.png
LV_IMG_DECLARE(ui_img_materialsymbolsplaycircle_png);    // assets/MaterialSymbolsPlayCircle.png
LV_IMG_DECLARE(ui_img_materialsymbolspausecirclerounded_png);    // assets/MaterialSymbolsPauseCircleRounded.png
LV_IMG_DECLARE(ui_img_fluentnext20filled_png);    // assets/FluentNext20Filled.png
LV_IMG_DECLARE(ui_img_fluentprevious24filled_png);    // assets/FluentPrevious24Filled.png
LV_IMG_DECLARE(ui_img_1452209827);    // assets/cold-1293305_1280.png
LV_IMG_DECLARE(ui_img_230494180);    // assets/flat-design-2307381_1280.png
LV_IMG_DECLARE(ui_img_1071127293);    // assets/icons-8821556_1280.png
LV_IMG_DECLARE(ui_img_iu_bg2_png);    // assets/iu_bg2.png
LV_IMG_DECLARE(ui_img_178944631);    // assets/pause-button-2148106_1280.png
LV_IMG_DECLARE(ui_img_1364712013);    // assets/rss-2440955_1280.png
LV_IMG_DECLARE(ui_img_wifi1_png);    // assets/wifi1.png



LV_FONT_DECLARE(ui_font_Number);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
