// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif


void Drain_Open(lv_event_t * e);
void Drain_Close(lv_event_t * e);
void NFC_Open(lv_event_t * e);
void NFC_Close(lv_event_t * e);
void Bluetooth_Open(lv_event_t * e);
void Bluetoorh_Close(lv_event_t * e);
void Wifi_Open(lv_event_t * e);
void Wifi_Close(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
