// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Update_Home_Time(lv_event_t * e);
void Update_Home_Date(lv_event_t * e);
void Motor_Toggle(lv_event_t * e);
void Update_Navi_Date(lv_event_t * e);
void Update_Humidity_Arc(lv_event_t * e);
void Update_Tempature_Arc(lv_event_t * e);
void Update_Step_Arc(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
