// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#include "ui.h"

void Update_Home_Time(lv_event_t * e)
{
	// Your code here
}

void Update_Home_Date(lv_event_t * e)
{
	// Your code here
}

void Drain_Open(lv_event_t * e)
{
	// Your code here
}

void Drain_Close(lv_event_t * e)
{
	// Your code here
}

void NFC_Open(lv_event_t * e)
{
	// Your code here
}

void NFC_Close(lv_event_t * e)
{
	// Your code here
}

void Bluetooth_Open(lv_event_t * e)
{
	// Your code here
}

void Bluetoorh_Close(lv_event_t * e)
{
	// Your code here
}

void Wifi_Open(lv_event_t * e)
{
	// Your code here
}

void Wifi_Close(lv_event_t * e)
{
	// Your code here
}

void Update_Navi_Date(lv_event_t * e)
{
	// Your code here
}

void Update_Step(lv_event_t * e)
{
	// Your code here
}

void Update_Tempature(lv_event_t * e)
{
	// Your code here
}

void Update_Humidity(lv_event_t * e)
{
	// Your code here
}

void Update_Humidity_Arc(lv_event_t * e)
{
	// Your code here
}

void Update_Tempature_Arc(lv_event_t * e)
{
	// Your code here
}

void Update_Step_Arc(lv_event_t * e)
{
	// Your code here
}

void Update_Light_Intensity(lv_event_t * e)
{
	// Your code here
}
