// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#include "../ui.h"

void ui_HomePage1_screen_init(void)
{
    ui_HomePage1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_HomePage1, &ui_img_iu_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockNumberLabel = lv_label_create(ui_HomePage1);
    lv_obj_set_width(ui_ClockNumberLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockNumberLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockNumberLabel, -1);
    lv_obj_set_y(ui_ClockNumberLabel, 72);
    lv_obj_set_align(ui_ClockNumberLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockNumberLabel, "15:20");
    lv_obj_set_style_text_color(ui_ClockNumberLabel, lv_color_hex(0xF3E7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClockNumberLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ClockNumberLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClockNumberLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_HomePage1);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, -2);
    lv_obj_set_y(ui_DateLabel, 107);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "SAT 14");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0xF3E7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DateLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ClockNumberLabel, ui_event_ClockNumberLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DateLabel, ui_event_DateLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomePage1, ui_event_HomePage1, LV_EVENT_ALL, NULL);

}
