// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#include "../ui.h"

void ui_AlarmPage_screen_init(void)
{
    ui_AlarmPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AlarmPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
