// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#include "../ui.h"

void ui_HomePage2_screen_init(void)
{
    ui_HomePage2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_HomePage2, &ui_img_iu_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockNumberLabel2 = lv_label_create(ui_HomePage2);
    lv_obj_set_width(ui_ClockNumberLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockNumberLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockNumberLabel2, -1);
    lv_obj_set_y(ui_ClockNumberLabel2, 72);
    lv_obj_set_align(ui_ClockNumberLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockNumberLabel2, "15:20");
    lv_obj_set_style_text_color(ui_ClockNumberLabel2, lv_color_hex(0xF3E7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClockNumberLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ClockNumberLabel2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClockNumberLabel2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel2 = lv_label_create(ui_HomePage2);
    lv_obj_set_width(ui_DateLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel2, -2);
    lv_obj_set_y(ui_DateLabel2, 107);
    lv_obj_set_align(ui_DateLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel2, "SAT 14");
    lv_obj_set_style_text_color(ui_DateLabel2, lv_color_hex(0xF3E7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DateLabel2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ClockNumberLabel2, ui_event_ClockNumberLabel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DateLabel2, ui_event_DateLabel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomePage2, ui_event_HomePage2, LV_EVENT_ALL, NULL);

}
