// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#include "../ui.h"

void ui_MessageArc_screen_init(void)
{
    ui_MessageArc = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MessageArc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MessageArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MessageArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepArc = lv_arc_create(ui_MessageArc);
    lv_obj_set_width(ui_StepArc, 210);
    lv_obj_set_height(ui_StepArc, 210);
    lv_obj_set_align(ui_StepArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StepArc, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_StepArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_StepArc, 0, 10000);
    lv_arc_set_value(ui_StepArc, 5000);
    lv_obj_set_style_arc_color(ui_StepArc, lv_color_hex(0x6A6D73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_StepArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_StepArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_StepArc, lv_color_hex(0xFF0C00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_StepArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_StepArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_StepArc, lv_color_hex(0xFF0C00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StepArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StepArc, -1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempatureArc = lv_arc_create(ui_MessageArc);
    lv_obj_set_width(ui_TempatureArc, 160);
    lv_obj_set_height(ui_TempatureArc, 160);
    lv_obj_set_x(ui_TempatureArc, 1);
    lv_obj_set_y(ui_TempatureArc, 0);
    lv_obj_set_align(ui_TempatureArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempatureArc, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_TempatureArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_TempatureArc, 26);
    lv_obj_set_style_arc_color(ui_TempatureArc, lv_color_hex(0x6C6C70), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempatureArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempatureArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_TempatureArc, lv_color_hex(0x1FB308), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempatureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempatureArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempatureArc, lv_color_hex(0x18B208), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempatureArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempatureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempatureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempatureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempatureArc, -1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HumidityArc = lv_arc_create(ui_MessageArc);
    lv_obj_set_width(ui_HumidityArc, 110);
    lv_obj_set_height(ui_HumidityArc, 110);
    lv_obj_set_x(ui_HumidityArc, 1);
    lv_obj_set_y(ui_HumidityArc, 0);
    lv_obj_set_align(ui_HumidityArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumidityArc, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_HumidityArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_HumidityArc, 50);
    lv_obj_set_style_arc_color(ui_HumidityArc, lv_color_hex(0x6A6D73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HumidityArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_HumidityArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_HumidityArc, lv_color_hex(0x00CEF6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HumidityArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_HumidityArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HumidityArc, lv_color_hex(0x00CEF6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidityArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HumidityArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HumidityArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HumidityArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HumidityArc, -1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Stepimg = lv_img_create(ui_MessageArc);
    lv_img_set_src(ui_Stepimg, &ui_img_step_png);
    lv_obj_set_width(ui_Stepimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Stepimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Stepimg, -70);
    lv_obj_set_y(ui_Stepimg, 65);
    lv_obj_set_align(ui_Stepimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Stepimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Stepimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tempimg = lv_img_create(ui_MessageArc);
    lv_img_set_src(ui_Tempimg, &ui_img_temp_png);
    lv_obj_set_width(ui_Tempimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tempimg, -50);
    lv_obj_set_y(ui_Tempimg, 47);
    lv_obj_set_align(ui_Tempimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tempimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Tempimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Humidimg = lv_img_create(ui_MessageArc);
    lv_img_set_src(ui_Humidimg, &ui_img_materialsymbolshumiditypercentage_png);
    lv_obj_set_width(ui_Humidimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidimg, -32);
    lv_obj_set_y(ui_Humidimg, 29);
    lv_obj_set_align(ui_Humidimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Humidimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Humidimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidArcLabel = lv_label_create(ui_MessageArc);
    lv_obj_set_width(ui_HumidArcLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidArcLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidArcLabel, 0);
    lv_obj_set_y(ui_HumidArcLabel, 37);
    lv_obj_set_align(ui_HumidArcLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidArcLabel, "50");
    lv_obj_set_style_text_color(ui_HumidArcLabel, lv_color_hex(0x00CEF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidArcLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempArcLabel = lv_label_create(ui_MessageArc);
    lv_obj_set_width(ui_TempArcLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempArcLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempArcLabel, 0);
    lv_obj_set_y(ui_TempArcLabel, 57);
    lv_obj_set_align(ui_TempArcLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempArcLabel, "26");
    lv_obj_set_style_text_color(ui_TempArcLabel, lv_color_hex(0x18B208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempArcLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepArcLabel = lv_label_create(ui_MessageArc);
    lv_obj_set_width(ui_StepArcLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StepArcLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StepArcLabel, 0);
    lv_obj_set_y(ui_StepArcLabel, 78);
    lv_obj_set_align(ui_StepArcLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StepArcLabel, "3469");
    lv_obj_set_style_text_color(ui_StepArcLabel, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StepArcLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HumidArcLabel, ui_event_HumidArcLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempArcLabel, ui_event_TempArcLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StepArcLabel, ui_event_StepArcLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MessageArc, ui_event_MessageArc, LV_EVENT_ALL, NULL);

}
