// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Qi_Watch

#include "../ui.h"

void ui_MusicPage_screen_init(void)
{
    ui_MusicPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MusicPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicPage, lv_color_hex(0x9E0766), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MusicPage, lv_color_hex(0x50034B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_MusicPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_MusicPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MusicPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicPIc = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_MusicPIc, &ui_img_iu1_png);
    lv_obj_set_width(ui_MusicPIc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicPIc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicPIc, 2);
    lv_obj_set_y(ui_MusicPIc, -53);
    lv_obj_set_align(ui_MusicPIc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicPIc, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MusicPIc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MusicControl = lv_imgbtn_create(ui_MusicPage);
    lv_imgbtn_set_src(ui_MusicControl, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_play_png, NULL);
    lv_imgbtn_set_src(ui_MusicControl, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_suspend_png, NULL);
    lv_imgbtn_set_src(ui_MusicControl, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_play_png, NULL);
    lv_imgbtn_set_src(ui_MusicControl, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_suspend_png, NULL);
    lv_imgbtn_set_src(ui_MusicControl, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_suspend_png, NULL);
    lv_imgbtn_set_src(ui_MusicControl, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_play_png, NULL);
    lv_obj_set_height(ui_MusicControl, 40);
    lv_obj_set_width(ui_MusicControl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MusicControl, 0);
    lv_obj_set_y(ui_MusicControl, 60);
    lv_obj_set_align(ui_MusicControl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicControl, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Next = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Next, &ui_img_next_png);
    lv_obj_set_width(ui_Next, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next, 50);
    lv_obj_set_y(ui_Next, 60);
    lv_obj_set_align(ui_Next, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Next, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_Next, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Back = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Back, &ui_img_back_png);
    lv_obj_set_width(ui_Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back, -50);
    lv_obj_set_y(ui_Back, 60);
    lv_obj_set_align(ui_Back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_MusicPage, ui_event_MusicPage, LV_EVENT_ALL, NULL);

}
